# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 05:58
from __future__ import unicode_literals

from django.db import migrations


def seed(apps, schema_editor):

    Service = apps.get_model('db', 'Service')
    Service(name='Yourporn').save()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed),
    ]
