# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170218_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_date',
            new_name='subscribe_date',
        ),
    ]
