# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees'
            },
        ),
    ]
