Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  [6379, 6380, 6381, 5672, 15672].each do |port|
    config.vm.network "forwarded_port", guest: port, host: port
  end
end
